@startuml

BaseEntity <- User
BaseEntity <- Document
Document <- DocumentType


class BaseEntity {
    -id
}

class Document {
    -model
    -DocumentType
}

class User {
    -name
}

enum DocumentType {
    -PDF
    -DOC
    -XLS
}

@enduml